apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: eureka-pod
      labels:
        app: eureka-app
    spec:
      containers:
        - name: eureka-container
          image: shubh1sinha/tour-eureak-server:3.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
  selector:
    matchLabels:
     app: eureka-app