apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: management-pod
      labels:
        app: management-app
    spec:
      containers:
        - name: management-container
          image: shubh1sinha/app-management-service:2.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
  selector:
    matchLabels:
     app: management-app