apiVersion: v1
kind: Service
metadata:
  name: management-service
  labels:
    app: management-app
spec:
  selector:
    app: management-app
  type: LoadBalancer
  ports:
  - nodePort: 30031
    port: 8381
    targetPort: 8381
