server:
 port: 8381

spring:
 application:
    name: app-management-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER:http://eureka-pod-0.eureka-service.default.svc.cluster.local:9190/eureka/}
debug: true 

   
management:
  endpoints:
    web:
      exposure:
        include: '*'  
  