apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: admin-pod
      labels:
        app: admin-app
    spec:
      containers:
        - name: admin-container
          image: shubh1sinha/app-admin-microservice:3.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8281
            protocol: 'TCP'
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: admin-mongo-secret
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: admin-mongo-secret 
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  key: database
                  name: admin-mongo-config
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: admin-mongo-config          
  selector:
    matchLabels:
     app: admin-app