apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
   
spec:
  replicas: 1
  template:
    metadata:
      name: employee-pod
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-container
          image: shubh1sinha/app-employee-microservice:3.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '50m'
              memory: '1G'
            requests:
              cpu: '1m'
              memory: '348Mi'
  selector:
    matchLabels:
     app: employee-app