server:
 port: 8281

spring:
 application:
    name: app-admin-microservice
 data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAM}'
      password: '${MONGO_PASSWORD}'
 cloud:
  kubernetes:
   secets:
    name: db-secret
   config: 
    enabled: true
    sources:
     - namespace: default
       name: mongo-conf
    reload:
     enables: true
     mode: polling
     period: 1000
   
 

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9190/eureka
debug: true 
