server:
 port: 8181


spring:
  application:
    name: app-employee-microservice
  data:
    mongodb:
      uri: mongodb://my-mongo-db:7Z7BO6KtvywlNTsF8rzAb9M3Wo22kmO9YTgKM4YLOcoMxlIUrflqpFsO98NMCMDT8AywuKt0Tk57ACDbgCLEHA==@my-mongo-db.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@my-mongo-db@
      database: employee
   


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:9190/eureka
debug: true 

